name: ARC Demo
on:
  workflow_dispatch:
jobs:
  Use-ARC:
    runs-on: pact.arc.runners-nowakmax-tools
    steps:
      - run: echo "🎉 Running on ARC self-hosted runner!"
      - run: sleep 10
      - run: echo "Repo:${{ github.repository }}, Ref:${{ github.ref }}"
